import {db,state,content,notice,requireUser,navigate,onCleanup,signOut} from './runtime.js'
import {html,httpsUrl,field} from './shared.js'
const avatar=p=>p.avatar_path?`<img class="profile-avatar" src="${html(httpsUrl(db.storage.from('avatars').getPublicUrl(p.avatar_path).data.publicUrl))}" alt="" loading="lazy" width="64" height="64">`:`<span class="profile-avatar">${html((p.display_name||p.username||'N')[0])}</span>`
let onlineIds=new Set()
let showOnlineOnly=false
export async function renderSocial(path){
  if(path==='/account')return account()
  if(path.startsWith('/people'))return people(path)
  if(path.startsWith('/messages/'))return conversation(path.slice(10))
  return inbox()
}
async function people(path){
  const generation=state.generation
  const username=path.split('/')[2]||null
  if(username)return profileDetail(decodeURIComponent(username))
  if(state.user){const [setup,photos]=await Promise.all([db.from('matching_profiles').select('matching_enabled,intro').eq('user_id',state.user.id).maybeSingle(),db.from('matching_photos').select('id',{count:'exact',head:true}).eq('user_id',state.user.id)]);if(!setup.data?.matching_enabled||!setup.data?.intro||!photos.count)return matchingOnboarding()}
  let items=[];let more=false
  let interest=''
  let activeIndex=0
  const paint=()=>{
    const visible=items.filter(p=>!showOnlineOnly||(p.show_online&&onlineIds.has(p.id)))
    if(activeIndex>=visible.length)activeIndex=0
    const p=visible[activeIndex]
    const tags=p?.people_interests||[]
    const score=p?Math.min(96,72+((p.username||'').length*3+tags.length*5)%25):0
    content(`<section class="matching-page matching-flow"><header class="matching-heading"><div><span>NITRA SPACE / MATCHING</span><h1>Jeden profil.<br><i>Jedno rozhodnutie.</i></h1></div><p>Prezri si človeka, jeho vibe a záujmy. Preskoč ho, otvor celý profil alebo pošli žiadosť o zoznámenie.</p></header><div class="matching-toolbar"><button data-online aria-pressed="${showOnlineOnly}"><i></i> ONLINE</button><label><span>HĽADAŤ PODĽA ZÁUJMU</span><input data-interest placeholder="hudba, šport, foto…" value="${html(interest)}" aria-label="Filtrovať podľa záujmu"></label><button data-filter>NÁJSŤ</button><a href="/account" data-route>MÔJ PROFIL ↗</a></div>${p?`<div class="matching-stage"><div class="matching-stack" aria-hidden="true"></div><article class="match-focus"><a class="match-focus-visual" href="/people/${html(p.username)}" data-route>${p.match_photo_url?`<img class="profile-avatar" src="${html(p.match_photo_url)}" alt="${html(p.display_name||p.username)}" loading="eager">`:avatar(p)}<span class="match-focus-shade"></span><div class="match-focus-top"><span>${String(activeIndex+1).padStart(2,'0')} / ${String(visible.length).padStart(2,'0')}</span><b>${p.show_online&&onlineIds.has(p.id)?'<i></i> TERAZ ONLINE':'NITRA'}</b></div><div class="match-focus-name"><small>@${html(p.username)}</small><h2>${html(p.display_name||p.username)}${p.is_verified?' <em aria-label="Overený účet">✓</em>':''}<b>${p.age}</b></h2></div></a><div class="match-focus-info"><div class="match-score"><strong>${score}%</strong><span>VIBE<br>ZHODA</span></div><div class="match-focus-bio"><span>O MNE</span><p>${html(p.status||p.bio||'Som otvorený/á novým ľuďom a dobrým rozhovorom.')}</p></div><div class="match-focus-tags"><span>ZÁUJMY</span><div class="interest-tags">${tags.slice(0,5).map(t=>`<b>${html(t)}</b>`).join('')||'<b>nové kontakty</b>'}</div></div><div class="match-safety">Presnú polohu ani dátum narodenia nezobrazujeme.</div><div class="match-decision"><button class="match-skip" data-skip aria-label="Preskočiť profil">×<span>PRESKOČIŤ</span></button><a href="/people/${html(p.username)}" data-route><span>PROFIL</span>↗</a><button class="match-like" data-talk="${p.id}">♡<span>SPOZNAŤ</span></button></div></div></article></div>`:'<section class="matching-empty"><span>00</span><h2>Zatiaľ ticho.</h2><p>Zmeň filter alebo si nastav viditeľnosť profilu.</p><a href="/account" data-route>NASTAVIŤ PROFIL →</a></section>'}${more?'<button class="load-more matching-more">NAČÍTAŤ ĎALŠIE PROFILY →</button>':''}</section>`)
    document.querySelector('[data-online]').onclick=()=>{showOnlineOnly=!showOnlineOnly;paint()}
    document.querySelector('[data-filter]').onclick=()=>{interest=document.querySelector('[data-interest]').value.trim();items=[];load().catch(()=>notice('Filtrovanie zlyhalo.'))}
    document.querySelector('[data-skip]')?.addEventListener('click',()=>{activeIndex=(activeIndex+1)%visible.length;paint()})
    document.querySelector('.load-more')?.addEventListener('click',e=>{e.currentTarget.disabled=true;load().catch(()=>notice('Načítanie zlyhalo.'))})
    document.querySelectorAll('[data-talk]').forEach(button=>button.onclick=()=>requestTalk(button))
    document.querySelectorAll('.person').forEach(card=>{const link=card.querySelector('a[href^="/people/"]');if(!link)return;card.classList.add('person-clickable');card.tabIndex=0;card.setAttribute('role','link');card.onclick=event=>{if(event.target.closest('a,button'))return;navigate(link.getAttribute('href'))};card.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('a,button')){event.preventDefault();navigate(link.getAttribute('href'))}}})
  }
  const load=async()=>{const {data,error}=await db.rpc('nitra_community_people',{p_after:items.at(-1)?.username||'',p_username:username,p_interest:interest});if(error)throw error;if(generation!==state.generation)return;const ids=data.map(p=>p.id);if(state.user&&ids.length){const photoRows=await db.from('matching_photos').select('user_id,storage_path,position').in('user_id',ids).eq('position',1);if(!photoRows.error&&photoRows.data?.length){const signed=await db.storage.from('matching-photos').createSignedUrls(photoRows.data.map(row=>row.storage_path),600);signed.data?.forEach((entry,index)=>{const person=data.find(p=>p.id===photoRows.data[index].user_id);if(person&&entry.signedUrl)person.match_photo_url=httpsUrl(entry.signedUrl)})}}items.push(...data);more=data.length===20;paint()}
  await load()
  const channel=db.channel('community-people-online').on('presence',{event:'sync'},()=>{onlineIds=new Set(Object.values(channel.presenceState()).flat().map(p=>p.user_id));if(generation===state.generation&&document.activeElement?.tagName!=='INPUT')paint()}).subscribe()
  onCleanup(()=>db.removeChannel(channel))
}
export async function matchingOnboarding(){
  const [profileResult,matchingResult,photosResult,interestsResult,chosenResult]=await Promise.all([db.from('profiles').select('display_name,username').eq('id',state.user.id).single(),db.from('matching_profiles').select('intro').eq('user_id',state.user.id).maybeSingle(),db.from('matching_photos').select('id,storage_path,position').eq('user_id',state.user.id).order('position'),db.from('interests').select('id,display_name').order('sort_order'),db.from('matching_profile_interests').select('interest_id').eq('user_id',state.user.id)])
  const profile=profileResult.data||{},matching=matchingResult.data||{intro:''},photos=photosResult.data||[],chosen=new Set((chosenResult.data||[]).map(row=>row.interest_id));let urls={}
  if(photos.length){const signed=await db.storage.from('matching-photos').createSignedUrls(photos.map(photo=>photo.storage_path),600);signed.data?.forEach((entry,index)=>{if(entry.signedUrl)urls[photos[index].position]=httpsUrl(entry.signedUrl)})}
  content(`<section class="matching-onboarding"><header><span>NITRA SPACE / TVOJ MATCHING PROFIL</span><b data-wizard-progress>01 — 03</b></header><div class="matching-onboarding-grid"><aside><span>VITAJ, ${html((profile.display_name||profile.username||'TY').toUpperCase())}</span><h1>Najprv ukáž,<br><i>kto si.</i></h1><p>Tri krátke kroky. Ty rozhoduješ, čo ostatní uvidia. Presnú polohu ani dátum narodenia nikdy nezverejníme.</p><ol><li class="active">Tvoj vibe</li><li>O tebe</li><li>Tvoje fotky</li></ol></aside><form data-matching-wizard><section class="wizard-step active" data-step="0"><small>KROK 01</small><h2>Čo ťa baví?</h2><p>Vyber aspoň 2 a najviac 8 záujmov. Podľa nich ti budeme ukazovať vhodnejšie profily.</p><fieldset class="matching-interest-picker">${(interestsResult.data||[]).map(item=>`<label><input type="checkbox" name="match_interest" value="${html(item.id)}" ${chosen.has(item.id)?'checked':''}><span>${html(item.display_name)}</span></label>`).join('')}</fieldset><button type="button" data-wizard-next>POKRAČOVAŤ →</button></section><section class="wizard-step" data-step="1"><small>KROK 02</small><h2>Povedz niečo o sebe.</h2><p>Jedna konkrétna veta funguje lepšie než všeobecný popis.</p><label>MOJE PREDSTAVENIE<textarea name="intro" maxlength="300" placeholder="Napríklad: Hudba, večerné prechádzky a dobrá káva…">${html(matching.intro)}</textarea><b data-intro-count>${matching.intro.length}/300</b></label><div class="wizard-actions"><button type="button" data-wizard-back>← SPÄŤ</button><button type="button" data-wizard-next>POKRAČOVAŤ →</button></div></section><section class="wizard-step" data-step="2"><small>KROK 03</small><h2>Vyber svoje fotky.</h2><p>Prvá je hlavná. Pridaj jasný portrét; ďalšie môžu ukázať postavu, aktivitu alebo tvoj štýl.</p><div class="wizard-photo-grid">${[1,2,3].map(position=>`<label class="wizard-photo ${urls[position]?'filled':''}" data-wizard-photo-slot="${position}">${urls[position]?`<img src="${html(urls[position])}" alt="Fotografia ${position}">`:`<strong>${position===1?'01':'0'+position}</strong><span>${position===1?'HLAVNÁ FOTKA':'PRIDAŤ FOTKU'}</span>`}<input type="file" accept="image/jpeg,image/png,image/webp" data-wizard-photo="${position}"></label>`).join('')}</div><small class="wizard-photo-tip">Automaticky orežeme na 4:5. JPG, PNG alebo WebP.</small><div class="wizard-actions"><button type="button" data-wizard-back>← SPÄŤ</button><button type="submit">DOKONČIŤ A ZAPNÚŤ MATCHING →</button></div></section></form></div></section>`)
  const form=document.querySelector('[data-matching-wizard]'),steps=[...form.querySelectorAll('.wizard-step')],nav=[...document.querySelectorAll('.matching-onboarding aside li')];let step=0,currentPhotos=[...photos]
  const show=index=>{step=index;steps.forEach((el,i)=>el.classList.toggle('active',i===step));nav.forEach((el,i)=>el.classList.toggle('active',i===step));document.querySelector('[data-wizard-progress]').textContent=`0${step+1} — 03`;scrollTo({top:0,behavior:'smooth'})}
  form.querySelectorAll('[data-wizard-next]').forEach(button=>button.onclick=()=>{if(step===0){const count=form.querySelectorAll('[name="match_interest"]:checked').length;if(count<2||count>8){notice('Vyber 2 až 8 záujmov.');return}}if(step===1&&form.intro.value.trim().length<20){notice('Napíš o sebe aspoň 20 znakov.');return}show(Math.min(2,step+1))})
  form.querySelectorAll('[data-wizard-back]').forEach(button=>button.onclick=()=>show(Math.max(0,step-1)))
  form.intro.oninput=()=>document.querySelector('[data-intro-count]').textContent=`${form.intro.value.length}/300`
  form.querySelectorAll('[data-wizard-photo]').forEach(input=>input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const position=Number(input.dataset.wizardPhoto);try{input.disabled=true;notice('Fotku spracúvame…');const blob=await matchingImage(file),path=`${state.user.id}/${position}.jpg`;const upload=await db.storage.from('matching-photos').upload(path,blob,{contentType:'image/jpeg',upsert:true});if(upload.error)throw upload.error;if(!currentPhotos.some(photo=>photo.position===position)){const inserted=await db.from('matching_photos').insert({user_id:state.user.id,storage_path:path,position}).select().single();if(inserted.error)throw inserted.error;currentPhotos.push(inserted.data)}const url=URL.createObjectURL(blob),slot=document.querySelector(`[data-wizard-photo-slot="${position}"]`);slot.classList.add('filled');slot.querySelector('img')?.remove();slot.insertAdjacentHTML('afterbegin',`<img src="${url}" alt="Fotografia ${position}">`);notice('Fotka je pripravená.');input.disabled=false}catch(error){notice(error.message||'Fotku sa nepodarilo uložiť.');input.disabled=false}})
  form.onsubmit=async event=>{event.preventDefault();if(!currentPhotos.some(photo=>photo.position===1)){notice('Najprv pridaj hlavnú fotografiu.');return}const selected=[...form.querySelectorAll('[name="match_interest"]:checked')].map(input=>input.value),button=form.querySelector('[type="submit"]');button.disabled=true;const saved=await db.rpc('save_matching_profile',{p_enabled:true,p_intro:form.intro.value.trim(),p_interest_ids:selected});if(saved.error){notice(saved.error.message);button.disabled=false;return}notice('Profil je pripravený. Vitaj v matchingu!');navigate('/people')}
}
async function profileDetail(username){
  const generation=state.generation
  const result=await db.rpc('nitra_community_people',{p_after:'',p_username:username,p_interest:''})
  if(result.error)throw result.error
  const person=result.data?.[0]
  if(!person){content('<section class="empty"><h1>Profil nie je dostupný.</h1><p>Môže byť súkromný, zablokovaný alebo odstránený.</p><a href="/people" data-route>← Späť na ľudí</a></section>');return}
  const [matching,photos]=await Promise.all([
    db.from('matching_profiles').select('intro,matching_enabled').eq('user_id',person.id).maybeSingle(),
    db.from('matching_photos').select('storage_path,position').eq('user_id',person.id).order('position',{ascending:true}).limit(3)
  ])
  if(generation!==state.generation)return
  let photoUrls=[]
  if(!photos.error&&photos.data?.length){const signed=await db.storage.from('matching-photos').createSignedUrls(photos.data.map(photo=>photo.storage_path),300);if(!signed.error)photoUrls=signed.data.map(item=>httpsUrl(item.signedUrl)).filter(Boolean)}
  const mainVisual=photoUrls.length?`<div class="public-profile-gallery">${photoUrls.map((url,index)=>`<img src="${html(url)}" alt="${html(person.display_name||person.username)} — fotografia ${index+1}" ${index?'loading="lazy"':''}>`).join('')}</div>`:`<div class="public-profile-fallback">${avatar(person)}</div>`
  content(`<article class="public-profile"><a class="public-profile-back" href="/people" data-route>← Späť na matching</a><div class="public-profile-card">${mainVisual}<div class="public-profile-copy"><span>MATCHING PROFIL</span><h1>${html(person.display_name||person.username)}${person.is_verified?' <i aria-label="Overený účet">✓</i>':''}, ${person.age}</h1><p class="public-profile-handle">@${html(person.username)}${person.show_online&&onlineIds.has(person.id)?' · online':''}</p><p class="public-profile-intro">${html(matching.data?.intro||person.status||person.bio||'Zatiaľ bez popisu.')}</p><div class="interest-tags">${(person.people_interests||[]).map(tag=>`<span>${html(tag)}</span>`).join('')}</div><div class="public-profile-actions"><button data-profile-talk="${person.id}">SPOZNAŤ →</button>${state.user&&state.user.id!==person.id?`<button data-profile-block="${person.id}">Blokovať</button>`:''}</div><small>Presnú polohu ani dátum narodenia nezobrazujeme.</small></div></div></article>`)
  const talkButton=document.querySelector('[data-profile-talk]');if(state.user?.id===person.id){talkButton.textContent='UPRAVIŤ PROFIL →';talkButton.onclick=()=>navigate('/account')}else talkButton?.addEventListener('click',event=>requestTalk(event.currentTarget))
  document.querySelector('[data-profile-block]')?.addEventListener('click',async event=>{if(!confirm('Zablokovať tento účet?'))return;event.currentTarget.disabled=true;const blocked=await db.from('blocks').insert({blocker_id:state.user.id,blocked_id:event.currentTarget.dataset.profileBlock});if(blocked.error){notice(blocked.error.message);event.currentTarget.disabled=false}else navigate('/people')})
}
async function requestTalk(button){
  if(!await requireUser())return
  button.disabled=true;const target=button.dataset.profileTalk||button.dataset.talk;const {data,error}=await db.rpc('matching_decide',{p_target:target,p_like:true})
  if(error){notice(error.message);button.disabled=false;return}
  if(data==='match'){const conversation=await db.rpc('get_or_create_dm',{p_other_user_id:target});if(conversation.error)notice(conversation.error.message);else navigate(`/messages/${conversation.data}`);return}
  button.textContent='Záujem uložený';notice('Tvoj záujem je súkromný. Rozhovor sa otvorí až po vzájomnom lajku.')
}
async function matchingImage(file){
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12*1024*1024)throw new Error('Použi JPG, PNG alebo WebP do 12 MB.')
  const bitmap=await createImageBitmap(file),ratio=4/5
  let sx=0,sy=0,sw=bitmap.width,sh=bitmap.height
  if(sw/sh>ratio){sw=Math.round(sh*ratio);sx=Math.round((bitmap.width-sw)/2)}else{sh=Math.round(sw/ratio);sy=Math.round((bitmap.height-sh)/2)}
  const canvas=document.createElement('canvas');canvas.width=960;canvas.height=1200
  canvas.getContext('2d').drawImage(bitmap,sx,sy,sw,sh,0,0,960,1200);bitmap.close()
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.86))
  if(!blob)throw new Error('Fotku sa nepodarilo spracovať.')
  return blob
}
async function account(){
  if(!state.user)return authForm(/#signup(?:\/|$)/i.test(location.hash))
  const [profileResult,blocked,matchingResult,photoResult,interestsResult,chosenResult]=await Promise.all([
    db.from('profiles').select('id,username,display_name,bio,avatar_path,discoverable,show_online,people_interests').eq('id',state.user.id).single(),db.rpc('list_blocked_accounts'),
    db.from('matching_profiles').select('matching_enabled,intro').eq('user_id',state.user.id).maybeSingle(),db.from('matching_photos').select('id,storage_path,position').eq('user_id',state.user.id).order('position'),
    db.from('interests').select('id,display_name').order('sort_order'),db.from('matching_profile_interests').select('interest_id').eq('user_id',state.user.id)
  ])
  if(profileResult.error)throw profileResult.error
  const p=profileResult.data,matching=matchingResult.data||{matching_enabled:false,intro:''},photos=photoResult.data||[],chosen=new Set((chosenResult.data||[]).map(row=>row.interest_id))
  let matchingPhotoUrls={}
  if(photos.length){const signed=await db.storage.from('matching-photos').createSignedUrls(photos.map(photo=>photo.storage_path),600);signed.data?.forEach((entry,index)=>{if(entry.signedUrl)matchingPhotoUrls[photos[index].position]=httpsUrl(entry.signedUrl)})}
content(`<section class="account-heading"><span>NITRA SPACE / NASTAVENIA</span><h1 class="spaced-account-title"><span>Tvoj</span><span>priestor.</span></h1><p>Profil, súkromie a bezpečnosť na jednom mieste.</p></section><div class="account-settings-grid"><form class="panel account-profile" data-profile><div class="settings-title"><span>01</span><div><h2>Profil</h2><p>To, čo o tebe uvidia ostatní.</p></div></div>${avatar(p)}${field('display_name','Meno',p.display_name)}${field('username','Používateľské meno',p.username)}<label>O mne<textarea name="bio" maxlength="500">${html(p.bio)}</textarea></label>${field('interests','Záujmy oddelené čiarkou',p.people_interests.join(', '))}<div class="settings-switches"><label><input type="checkbox" name="discoverable" ${p.discoverable?'checked':''}><span><b>Zobraziť ma medzi ľuďmi</b><small>Profil sa môže objaviť v sekcii Ľudia.</small></span></label><label><input type="checkbox" name="show_online" ${p.show_online?'checked':''}><span><b>Ukazovať online stav</b><small>Ostatní uvidia, keď si aktívny.</small></span></label></div><p class="muted">Nikdy nezobrazujeme dátum narodenia ani presnú GPS polohu.</p><button class="settings-primary">Uložiť zmeny</button></form><div class="account-settings-side"><form class="panel" data-status><div class="settings-title"><span>02</span><div><h2>Status</h2><p>Krátka poznámka na 24 hodín.</p></div></div>${field('body','Čo máš nové?')}<button>Zverejniť status</button></form><section class="panel"><div class="settings-title"><span>03</span><div><h2>Blokované účty</h2><p>Spravuj ľudí, ktorých nechceš vidieť.</p></div></div>${(blocked.data||[]).map(b=>`<div class="blocked-row"><span>${html(b.display_name||b.username)}</span><button data-unblock="${html(b.id||b.blocked_id)}">Odblokovať</button></div>`).join('')||'<p class="muted">Nemáš žiadne blokované účty.</p>'}</section><section class="panel account-security"><div class="settings-title"><span>04</span><div><h2>Bezpečnosť</h2><p>${html(state.user.email||'Prihlásený účet')}</p></div></div><div class="settings-actions">${state.admin?'<a href="/admin/news" data-route>Redakčný admin <b>↗</b></a>':''}<button data-logout>Odhlásiť sa <b>→</b></button></div></section><section class="panel danger-zone"><span>NEBEZPEČNÁ ZÓNA</span><h2>Vymazanie účtu</h2><p>Natrvalo odstráni profil aj prístup k účtu. Túto akciu nebude možné vrátiť späť.</p><button type="button" data-delete-account>Vymazať účet</button></section></div></div>`)
  document.querySelector('.account-settings-side').insertAdjacentHTML('afterbegin',`<form class="panel matching-editor" data-matching><div class="settings-title"><span>M</span><div><h2>Matching profil</h2><p>Samostatná vizitka pre spoznávanie.</p></div></div><label class="matching-master"><input type="checkbox" name="enabled" ${matching.matching_enabled?'checked':''}><span><b>Zobraziť ma v matchingu</b><small>Kedykoľvek môžeš profil skryť.</small></span></label><label>Krátke predstavenie<textarea name="intro" maxlength="300" placeholder="Čo má o tebe človek vedieť?">${html(matching.intro)}</textarea><small>Maximálne 300 znakov. Buď konkrétny a prirodzený.</small></label><fieldset class="matching-interest-picker"><legend>Čo ťa baví · max. 8</legend>${(interestsResult.data||[]).map(item=>`<label><input type="checkbox" name="match_interest" value="${html(item.id)}" ${chosen.has(item.id)?'checked':''}><span>${html(item.display_name)}</span></label>`).join('')}</fieldset><div class="matching-photo-head"><div><b>Fotky do matchingu</b><small>Prvá je hlavná. Najlepšie funguje portrét 4:5.</small></div><span>${photos.length}/3</span></div><div class="matching-photo-grid">${[1,2,3].map(position=>`<div class="matching-photo-slot ${matchingPhotoUrls[position]?'has-photo':''}" data-photo-slot="${position}">${matchingPhotoUrls[position]?`<img src="${html(matchingPhotoUrls[position])}" alt="Matching fotografia ${position}">`:`<strong>${position===1?'HLAVNÁ':'+'}</strong><small>${position===1?'TVÁR MUSÍ BYŤ VIDIEŤ':'ĎALŠIA FOTKA'}</small>`}<label><input type="file" accept="image/jpeg,image/png,image/webp" data-match-photo="${position}"><span>${matchingPhotoUrls[position]?'VYMENIŤ':'PRIDAŤ'}</span></label>${matchingPhotoUrls[position]?`<button type="button" data-remove-match-photo="${position}">Odstrániť</button>`:''}</div>`).join('')}</div><p class="matching-photo-note">JPG, PNG alebo WebP. Fotku automaticky orežeme na 4:5 a zmenšíme.</p><button class="settings-primary">Uložiť matching profil</button></form>`)
  const matchingForm=document.querySelector('[data-matching]')
  matchingForm.onsubmit=async event=>{event.preventDefault();const selected=[...matchingForm.querySelectorAll('[name="match_interest"]:checked')].map(input=>input.value);if(selected.length>8){notice('Vyber najviac 8 záujmov.');return}const button=matchingForm.querySelector('.settings-primary');button.disabled=true;const result=await db.rpc('save_matching_profile',{p_enabled:matchingForm.enabled.checked,p_intro:matchingForm.intro.value,p_interest_ids:selected});notice(result.error?result.error.message:'Matching profil je uložený.');button.disabled=false}
  matchingForm.querySelectorAll('[data-match-photo]').forEach(input=>input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const position=Number(input.dataset.matchPhoto);try{input.disabled=true;notice('Fotku spracúvame…');const blob=await matchingImage(file);const path=`${state.user.id}/${position}.jpg`;const upload=await db.storage.from('matching-photos').upload(path,blob,{contentType:'image/jpeg',upsert:true});if(upload.error)throw upload.error;const existing=photos.find(photo=>photo.position===position);if(!existing){const inserted=await db.from('matching_photos').insert({user_id:state.user.id,storage_path:path,position});if(inserted.error)throw inserted.error}notice('Fotka bola uložená.');account()}catch(error){notice(error.message||'Fotku sa nepodarilo uložiť.');input.disabled=false}})
  matchingForm.querySelectorAll('[data-remove-match-photo]').forEach(button=>button.onclick=async()=>{const position=Number(button.dataset.removeMatchPhoto),photo=photos.find(item=>item.position===position);if(!photo||!confirm('Odstrániť túto fotku?'))return;button.disabled=true;const removed=await db.from('matching_photos').delete().eq('id',photo.id);if(removed.error){notice(removed.error.message);button.disabled=false;return}await db.storage.from('matching-photos').remove([photo.storage_path]);notice('Fotka bola odstránená.');account()})
  const form=document.querySelector('[data-profile]');form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form));const result=await db.from('profiles').update({display_name:v.display_name.trim(),username:v.username.trim().toLowerCase(),bio:v.bio,people_interests:v.interests.split(',').map(t=>t.trim()).filter(Boolean).slice(0,8),discoverable:form.discoverable.checked,show_online:form.show_online.checked}).eq('id',state.user.id);if(result.error)notice(result.error.message);else{window.dispatchEvent(new Event('community-privacy-change'));notice('Nastavenia uložené.')}}
  document.querySelector('[data-status]').onsubmit=async e=>{e.preventDefault();const body=new FormData(e.currentTarget).get('body');const {error}=await db.rpc('set_status',{p_body:body,p_visibility:'public'});notice(error?error.message:'Status zverejnený.')}
  document.querySelector('[data-logout]').onclick=signOut
  document.querySelector('[data-delete-account]').onclick=async e=>{
    const phrase=prompt('Táto akcia je trvalá. Pre potvrdenie napíš VYMAZAŤ.')
    if(phrase!=='VYMAZAŤ')return
    e.currentTarget.disabled=true
    const {error}=await db.functions.invoke('delete-account')
    if(error){notice('Účet sa nepodarilo vymazať. Skús to neskôr.');e.currentTarget.disabled=false;return}
    await signOut()
  }
  document.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=async()=>{const {error}=await db.rpc('unblock_user',{p_blocked:b.dataset.unblock});if(error)notice(error.message);else account()})
}
function authForm(signup=false){
 content(`<section class="panel auth-form"><span>NITRA SPACE / ÚČET</span><h1>${signup?'Vytvor si účet.':'Vitaj späť.'}</h1><form data-supa-auth><label>E-mail<input name="email" type="email" required autocomplete="email"></label><label>Heslo<input name="password" type="password" required minlength="6" autocomplete="${signup?'new-password':'current-password'}"></label><p class="form-message" role="alert"></p><button type="submit">${signup?'Zaregistrovať sa':'Prihlásiť sa'} →</button></form><button type="button" data-auth-switch>${signup?'Už mám účet':'Vytvoriť účet'}</button><button type="button" data-reset-password>Zabudol som heslo</button></section>`)
 document.querySelector('[data-auth-switch]').onclick=()=>navigate(signup?'/account':'/account#signup')
 document.querySelector('[data-reset-password]').onclick=async()=>{const email=document.querySelector('[data-supa-auth] input[name=email]').value.trim();if(!email){notice('Najprv zadaj e-mail.');return}const r=await db.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/account`});notice(r.error?r.error.message:'Odkaz na reset hesla sme poslali na e-mail.')}
 document.querySelector('[data-supa-auth]').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget, values=Object.fromEntries(new FormData(form)), button=form.querySelector('button[type=submit]');button.disabled=true;const result=signup?await db.auth.signUp({email:values.email,password:values.password}):await db.auth.signInWithPassword({email:values.email,password:values.password});if(result.error)notice(result.error.message);else if(signup&&!result.data.session)notice('Skontroluj e-mail a potvrď registráciu.');else{state.user=result.data.user;notice('Prihlásenie úspešné.');navigate('/account')}button.disabled=false}
}
async function inbox(){
  content('<section class="page-heading"><span>JEDEN ROZHOVOR MÔŽE NIEČO ZMENIŤ.</span><h1>Spoj sa.</h1></section><a class="random-link panel" href="/chat.html?return=%2Fmessages"><h2>Random anonymous chat ↗</h2><p>Bez profilu. Bez tlaku. Existujúci anonymný chat.</p></a><section id="inbox"></section>')
  if(!state.user){document.querySelector('#inbox').innerHTML='<section class="panel"><h2>Súkromné správy</h2><a href="/account" data-route>Prihlás sa pre žiadosti a konverzácie →</a></section>';return}
  const generation=state.generation
  const load=async()=>{
    const [requests,chats,notifications]=await Promise.all([db.rpc('request_inbox'),db.rpc('nitra_community_inbox'),db.from('notifications').select('id,type,read_at').is('read_at',null).limit(100)])
    if(requests.error||chats.error)throw requests.error||chats.error
    if(generation!==state.generation)return
    document.querySelector('#inbox').innerHTML=`<h2>Žiadosti</h2>${(requests.data?.connection_requests||[]).map(r=>`<article class="panel request-row"><strong>${html(r.display_name||r.username)}</strong><div class="actions"><button data-accept="${r.id}">Prijať</button><button data-ignore="${r.id}">Ignorovať</button><button data-block="${r.id}">Blokovať</button></div></article>`).join('')||'<p class="muted">Žiadne nové žiadosti.</p>'}<h2>Konverzácie <small>${notifications.data?.length||0} neprečítaných upozornení</small></h2>${chats.data.map(c=>`<a class="conversation-row panel" data-route href="/messages/${c.id}">${avatar(c)}<div><strong>${html(c.display_name||c.username)}</strong><p>${c.unread?`${c.unread} nových správ`:'Otvoriť rozhovor'}</p></div>${c.unread?'<i aria-label="Nová správa"></i>':''}</a>`).join('')||'<p class="muted">Konverzácie vzniknú po prijatí žiadosti.</p>'}`
    for(const action of ['accept','ignore'])document.querySelectorAll(`[data-${action}]`).forEach(b=>b.onclick=async()=>{b.disabled=true;const r=await db.rpc('nitra_community_respond',{p_requester:b.dataset[action],p_accept:action==='accept'});if(r.error){notice(r.error.message);b.disabled=false}else if(r.data)navigate('/messages/'+r.data);else load()})
    bindBlocks()
  }
  await load();const timer=setInterval(()=>{if(!document.hidden)load().catch(()=>{})},5000);onCleanup(()=>clearInterval(timer))
}
function bindBlocks(){document.querySelectorAll('[data-block]').forEach(b=>b.onclick=async()=>{if(!confirm('Zablokovať tento účet? Existujúci rozhovor sa odstráni.'))return;const {error}=await db.from('blocks').insert({blocker_id:state.user.id,blocked_id:b.dataset.block});if(error)notice(error.message);else navigate('/messages')})}
async function conversation(id){
  if(!await requireUser())return
  if(!/^[0-9a-f-]{36}$/i.test(id)){notice('Neplatná konverzácia.');return}
  const generation=state.generation
  const {data:inbox,error}=await db.rpc('nitra_community_inbox');if(error)throw error
  const chat=inbox.find(c=>c.id===id);if(!chat){content('<section class="empty">Konverzácia nie je dostupná.</section>');return}
  content(`<section class="dm-shell"><header><a href="/messages" data-route>←</a><strong>${html(chat.display_name||chat.username)}</strong><button data-block="${chat.other_id}">Blokovať</button><button data-report>Nahlásiť</button></header><button data-older>Staršie správy</button><div class="dm-messages" aria-live="polite"></div><small data-typing></small><form class="dm-composer"><label class="sr-only" for="dm-input">Správa</label><input id="dm-input" name="body" maxlength="2000" autocomplete="off" placeholder="Napíš správu…" required><button>Poslať</button></form></section>`)
  let rows=[],oldest=null,signature='',sending=false,lastTyping=0,typingTimer
  const list=document.querySelector('.dm-messages');const form=document.querySelector('.dm-composer');const input=form.elements.namedItem('body')
  const paint=()=>{const bottom=list.scrollHeight-list.scrollTop-list.clientHeight<90;list.innerHTML=rows.map(m=>`<div class="dm-bubble ${m.sender_id===state.user.id?'mine':''}"><p>${html(m.body)}</p><small>${new Date(m.created_at).toLocaleTimeString('sk-SK',{hour:'2-digit',minute:'2-digit'})}</small>${m.sender_id===state.user.id?`<button data-delete-message="${m.id}" aria-label="Vymazať správu">×</button>`:''}</div>`).join('');if(bottom||sending)list.scrollTop=list.scrollHeight;list.querySelectorAll('[data-delete-message]').forEach(b=>b.onclick=async()=>{if(!confirm('Vymazať správu pre oboch?'))return;const r=await db.from('direct_messages').delete().eq('id',b.dataset.deleteMessage).eq('sender_id',state.user.id);if(r.error)notice(r.error.message);else{rows=rows.filter(m=>m.id!==b.dataset.deleteMessage);paint()}})}
  const load=async(older=false)=>{let q=db.from('direct_messages').select('id,sender_id,body,created_at').eq('conversation_id',id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(40);if(older&&oldest)q=q.lt('created_at',oldest);const {data,error}=await q;if(error)throw error;if(generation!==state.generation)return;if(older){rows=[...data.reverse(),...rows];oldest=rows[0]?.created_at;paint()}else{const next=data.reverse();const current=JSON.stringify(next);if(current!==signature){signature=current;rows=next;oldest=rows[0]?.created_at;paint()}}if(!document.hidden)await db.rpc('nitra_community_read',{p_conversation:id});document.querySelector('[data-older]').disabled=data.length<40}
  await load();list.scrollTop=list.scrollHeight
  const token=await db.auth.getSession();await db.realtime.setAuth(token.data.session?.access_token)
  const channel=db.channel(`dm:${id}`,{config:{private:true}}).on('broadcast',{event:'typing'},({payload})=>{if(payload?.sender!==chat.other_id)return;const el=document.querySelector('[data-typing]');if(!el)return;el.textContent=payload.active?'Píše…':'';clearTimeout(typingTimer);typingTimer=setTimeout(()=>{el.textContent=''},2500)}).subscribe()
  input.oninput=()=>{if(Date.now()-lastTyping<800)return;lastTyping=Date.now();channel.send({type:'broadcast',event:'typing',payload:{sender:state.user.id,active:!!input.value.trim()}})}
  const bottom=()=>{requestAnimationFrame(()=>{list.scrollTop=list.scrollHeight});setTimeout(()=>{list.scrollTop=list.scrollHeight},150)}
  input.onfocus=bottom
  form.onsubmit=async e=>{e.preventDefault();const body=input.value.trim();if(!body||sending)return;sending=true;form.querySelector('button').disabled=true;const {error}=await db.from('direct_messages').insert({conversation_id:id,sender_id:state.user.id,body});if(error)notice(error.message);else{input.value='';await channel.send({type:'broadcast',event:'typing',payload:{sender:state.user.id,active:false}});await load();bottom()}sending=false;form.querySelector('button').disabled=false;input.focus()}
  document.querySelector('[data-older]').onclick=()=>load(true).catch(()=>notice('Staršie správy sa nepodarilo načítať.'))
  document.querySelector('[data-report]').onclick=async()=>{const reason=prompt('Dôvod: spam, harassment, hate, sexual_content, impersonation, underage, other','spam');if(!reason)return;const r=await db.from('reports').insert({reporter_id:state.user.id,reported_user_id:chat.other_id,reason});notice(r.error?r.error.message:'Nahlásenie bolo odoslané.')}
  bindBlocks()
  document.body.classList.add('nitra-private-dm')
  const viewport=()=>{document.documentElement.style.setProperty('--dm-height',`${window.visualViewport?.height||innerHeight}px`);document.documentElement.style.setProperty('--dm-top',`${window.visualViewport?.offsetTop||0}px`);if(document.activeElement===input)bottom()}
  viewport();window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport)
  const timer=setInterval(()=>{if(!document.hidden)load().catch(()=>notice('Spojenie sa obnovuje…'))},4000)
  onCleanup(()=>{document.body.classList.remove('nitra-private-dm');clearInterval(timer);clearTimeout(typingTimer);window.visualViewport?.removeEventListener('resize',viewport);window.visualViewport?.removeEventListener('scroll',viewport);db.removeChannel(channel)})
}
