import test from 'node:test'
import assert from 'node:assert/strict'
import {html,httpsUrl,slugify} from '../src/features/shared.js'
import {fitHeadline,renderNewsCard} from '../server/news-card.js'
import {processNews,publicAddress,fingerprint,relevant,sensitive} from '../server/news-ingestion.js'
import {parseGoogleNewsRss,searchExpression,toDraft,verifyStories} from '../server/nitrak-discovery.js'
test('untrusted content and links are escaped',()=>{assert.equal(html('<img onerror="bad">'), '&lt;img onerror=&quot;bad&quot;&gt;');assert.equal(httpsUrl('javascript:alert(1)'),'');assert.equal(slugify('Nové správy z Nitry!'),'nove-spravy-z-nitry')})
test('long headlines fit within safe area including unbroken words',()=>{for(const title of ['Mesto žije.', 'Najnovšie správy '.repeat(15),'W'.repeat(180)]){const fit=fitHeadline(title);assert.ok(fit.lines.length<=6);assert.ok(fit.size>=48);fit.lines.forEach(line=>assert.ok(line.length*fit.size*.68<=936))}})
test('generated cards have feed/story dimensions and safe fallback',()=>{const card=renderNewsCard({headline:'<script>bad</script>',category:'Mesto'},'story','https://evil');assert.match(card,/height="1920"/);assert.ok(!card.includes('<script>'));assert.ok(!card.includes('https://evil'));assert.match(renderNewsCard({headline:'Nitra'}),/height="1350"/)})
test('pipeline is fail-closed and never publishes',async()=>{const item={title:'Nové námestie v Nitre',summary:'Mesto pripravuje nové námestie.',url:'https://example.com/nitra',published_at:'2026-09-02'};await assert.rejects(()=>processNews(item,{approved:false}));const draft=await processNews(item,{approved:true,id:'test',name:'Mesto'});assert.equal(draft.status,'draft');assert.equal(draft.manual_review_required,true);assert.equal(draft.cover_image_url,null);assert.equal(draft.fingerprint,fingerprint(item));assert.equal(relevant({title:'Praha',content:'Správy z Prahy'}),false);assert.equal(relevant({title:'Playboi Carti vydáva nový album',content:''},{scope:'global'}),true);assert.equal(relevant({title:'Playboi Carti vydáva nový album',content:''},{scope:'nitra'}),false);assert.equal(sensitive({title:'Polícia zasahovala',content:''}),true)})
test('source fetch rejects private/local IP space',()=>{for(const ip of ['127.0.0.1','10.2.3.4','169.254.169.254','172.16.1.2','192.168.1.1','::1','100.64.1.2'])assert.equal(publicAddress(ip),false);assert.equal(publicAddress('1.1.1.1'),true)})
test('saved topic discovery supports global rap while local mode remains strict',()=>{const now=Date.parse('2026-09-03T12:00:00Z');const xml=`<rss><channel><item><title>Nitra Music Week prinesie do mesta hudbu - nitralive.sk</title><link>https://news.google.com/articles/nitra-rap</link><source>nitralive.sk</source><pubDate>Sat, 01 Aug 2026 10:00:00 GMT</pubDate></item><item><title>Kanye a Carti pripravujú nový rapový projekt - Hudba.sk</title><link>https://news.google.com/articles/global-rap</link><source>Hudba.sk</source><pubDate>Sat, 01 Aug 2026 10:00:00 GMT</pubDate></item></channel></rss>`;const global=parseGoogleNewsRss(xml,now,'rap',400);const local=parseGoogleNewsRss(xml,now,'rap',400,{localOnly:true});assert.equal(global.length,2);assert.equal(local.length,1);assert.equal(global[1].source_name,'Hudba.sk');assert.match(searchExpression('rap'),/hip-hop/);assert.equal(toDraft(global[1],'rap').source_name,'Hudba.sk')})
test('automatic source metadata creates an original review-only article shell',()=>{const draft=toDraft({title:'Nový rapový album prichádza tento týždeň',url:'https://example.com/article',source_name:'Hudba.sk',source_description:'Interpret oznámil dátum vydania a predstavil prvý singel.',cover_image_url:'https://images.example.com/cover.jpg',image_credit:'Automaticky načítané zo zdroja Hudba.sk. Pred publikovaním over práva na použitie.'},'rap');assert.equal(draft.cover_image_url,'https://images.example.com/cover.jpg');assert.equal(draft.image_rights,'source_unverified');assert.equal(draft.status,'draft');assert.equal(draft.manual_review_required,true);assert.match(draft.image_credit,/over práva/i);assert.match(draft.summary,/dodatočné redakčné overenie/i);assert.doesNotMatch(draft.content,/Interpret oznámil dátum vydania/);assert.match(draft.content,/nie kopírovaním/i)})
test('story verification requires independent source names',()=>{const items=[{title:'MHD v Nitre čakajú zmeny počas výstavy',source_name:'Mesto Nitra',url:'https://example.com/a',published_at:'2026-09-04T10:00:00Z'},{title:'Počas výstavy čakajú MHD v Nitre veľké zmeny',source_name:'Nitrak.sk',url:'https://example.com/b',published_at:'2026-09-04T09:00:00Z'}];const stories=verifyStories(items);assert.equal(stories.length,1);assert.equal(stories[0].verified,true);assert.equal(stories[0].verification_sources.length,2);assert.match(toDraft(stories[0]).content,/najmenej 2 zdroje/i)})
test('current search rejects old articles and sorts newest first',()=>{const now=Date.parse('2026-09-04T12:00:00Z');const xml=`<rss><channel><item><title>Starý rapový rozhovor už nie je aktuálny - Hudba.sk</title><link>https://news.google.com/articles/old</link><source>Hudba.sk</source><pubDate>Sat, 01 Aug 2026 10:00:00 GMT</pubDate></item><item><title>Čerstvá rapová novinka z dnešného rána - Hudba.sk</title><link>https://news.google.com/articles/new</link><source>Hudba.sk</source><pubDate>Thu, 04 Sep 2026 08:00:00 GMT</pubDate></item><item><title>Včerajšia rapová novinka zo scény - Rap.sk</title><link>https://news.google.com/articles/yesterday</link><source>Rap.sk</source><pubDate>Wed, 03 Sep 2026 08:00:00 GMT</pubDate></item></channel></rss>`;const found=parseGoogleNewsRss(xml,now,'rap',3);assert.deepEqual(found.map(item=>item.url),['https://news.google.com/articles/new','https://news.google.com/articles/yesterday'])})
