import './chrome-next.css'
import './chrome-next-mobile.css'
import './features/editorial.css'
import {mount as mountFeature,cleanup as cleanupFeature} from './features/runtime.js'
import {createClient} from '@supabase/supabase-js'
import {createPreviewData} from './chrome-next-data.js'

const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY
const client=url&&key?createClient(url,key):null
const api=createPreviewData(client),root=document.querySelector('#chrome-app'),sheet=document.querySelector('#sheet')
const routes={board:'Nástenka',news:'NEWS',chat:'Chaty',polls:'Ankety',people:'Matching',events:'Eventy',account:'Účet'}
const paths={home:'M3 11 12 3l9 8M5 10v11h5v-7h4v7h5V10',chat:'M8 4h8a5 5 0 0 1 5 5v6a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5V9a5 5 0 0 1 5-5Z',events:'m12 2 10 10-10 10L2 12Z',people:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10',search:'M10.5 3a7.5 7.5 0 1 0 0 15 7.5 7.5 0 0 0 0-15M16 16l5 5',arrow:'M6 18 18 6M6 6h12v12',close:'m6 6 12 12M6 18 18-12',user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 21v-2a8 8 0 0 1 16 0v2Z',bell:'M5 17h14l-2-4V9a5 5 0 0 0-10 0v4ZM10 21h4',lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5ZM12 14v3',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7M3 21 21 3',heart:'M12 21 3 12C-2 5 7 0 12 7 17 0 26 5 21 12Z',chevron:'m9 5 7 7-7 7',logout:'M9 3H3v18h6M9 12h12m-5-5 5 5-5 5'}
const icon=(name)=>`<svg class="${name}-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.arrow}"/></svg>`
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const ornament=()=>'<i class="chrome" aria-hidden="true"></i>'
let route='',generation=0,cache={},filter='Všetky',register=false,returnFocus=null,toastTimer
const toast=message=>{const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),5000)}
const data=name=>cache[name]?.data||[]
const account=()=>cache.account?.status==='ready'?cache.account.data:null
const navLink=(id,label)=>`<a href="${['news','people','polls','account'].includes(id)?'/'+id:'/#'+id}" ${route===id?'aria-current="page"':''}>${label}</a>`
function shell(){root.innerHTML=`<header><a class="logo" href="/#board" aria-label="Nitra Space — domov"><span>NITRA</span><span>SPACE</span></a><nav class="desktop-nav" aria-label="Hlavná navigácia">${Object.entries(routes).map(([id,label])=>navLink(id,label)).join('')}</nav><div class="header-actions"><button class="circle" data-action="search" aria-label="Vyhľadať">${icon('search')}</button><a class="circle" href="/account" aria-label="Môj účet">${icon('user')}</a></div></header><main id="main"></main><nav class="bottom-nav" aria-label="Spodná navigácia">${[['board','home'],['chat','chat'],['news','events'],['people','people']].map(([id,i])=>navLink(id,icon(i)+routes[id])).join('')}</nav>`}
const hero=(name,title,sub,extra='')=>`<section class="hero ${name}">${ornament()}<div class="eyebrow">/ ${routes[name]?.toUpperCase()||name}</div><h1>${title.split('|').map(t=>`<span>${t}</span>`).join('')}</h1>${extra}${sub?`<p>${sub}</p>`:''}</section>`
const button=(href,label)=>`<a class="primary" href="${href}">${label}${icon('arrow')}</a>`
const chips=(items)=>`<div class="chips" aria-label="Filtrovanie">${items.map(t=>`<button data-filter="${esc(t)}" aria-pressed="${filter===t}">${esc(t)}</button>`).join('')}</div>`
function status(name,empty){const r=cache[name];if(!r)return '<div class="empty" role="status">Načítavam…</div>';if(r.status==='error')return `<div class="empty"><h2>Nepodarilo sa pripojiť.</h2><p>${esc(r.error)}</p><button data-action="retry">Skúsiť znova</button></div>`;if(!r.data?.length)return `<div class="empty">${empty}</div>`;return ''}
function home(){const shortcut=[['tellonym','Tellonym','https://tellonym.me/nitraspace'],['polls','Ankety','#polls'],['people','Matching','#people'],['account','Účet','#account']];return `<div class="page home"><section class="home-hero">${ornament()}<div class="coordinates">NITRA<br>SLOVAKIA<br>48.3067° N<br>18.0828° E</div><h1 class="home-title"><span>NITRA</span><span>SPACE</span></h1><p class="home-tagline">ONE CITY.<br>ONE SPACE.</p></section><div class="shortcuts">${shortcut.map(([id,label,href],i)=>`<a class="shortcut" href="${href}" ${id==='tellonym'?'target="_blank" rel="noopener noreferrer"':''}><small>0${i+1}</small>${ornament()}<strong>${label}</strong></a>`).join('')}</div><div class="stats"><div><b>${cache.events?.status==='ready'?data('events').length:'—'}</b><small>Eventov</small></div><div><b>${cache.people?.status==='ready'?data('people').length:'—'}</b><small>Profilov vo výbere</small></div><div><b>${cache.polls?.status==='ready'?data('polls').length:'—'}</b><small>Ankiet</small></div></div>${button('#chat','Objav Nitra Space')}</div>`}
function chat(){return `<div class="page chat">${hero('chat','NÁHODA|MÔŽE|ZAČAŤ.','BEZ PROFILU.<br>BEZ TLAKU.<br>LEN ROZHOVOR.')} ${button('/chat.html','Začať chat')}<div class="features"><div>${icon('lock')}ANONYMNE</div><div>${icon('eye')}ŽIADNE<br>OČAKÁVANIA</div><div>${icon('chat')}LEN<br>ROZHOVOR</div></div><div class="section-heading">Ľudia z Nitry</div>${data('people').length?`<div class="avatars">${data('people').slice(0,6).map(p=>`<button data-profile="${esc(p.username)}" aria-label="Profil ${esc(p.name)}">${avatar(p)}</button>`).join('')}</div>`:'<p class="muted">Rozhovor sa začína jedným klikom. Bez vymyslených profilov a počítadiel.</p>'}</div>`}
function pollCard(p,i){return `<article class="card poll-card"><div class="card-top"><span>${String(i+1).padStart(2,'0')}</span><span>${p.closesAt?'Do '+date(p.closesAt):'Anketa'}</span></div><h2>${esc(p.question)}</h2>${p.options.map(o=>`<button class="option ${p.resultsVisible?'':'voteable'}" data-poll="${esc(p.id)}" data-option="${esc(o.id)}" ${p.resultsVisible?'disabled':''}><span class="option-label"><span>${esc(o.label)}</span><span>${p.resultsVisible?`${o.percent??0}%`:icon('arrow')}</span></span>${p.resultsVisible?`<span class="track"><i style="width:${Math.max(0,Math.min(100,Number(o.percent)||0))}%"></i></span>`:''}</button>`).join('')}<p class="muted">${p.resultsVisible?`${p.totalVotes??0} hlasov · Tvoj hlas je uložený.`:'Hlasuj a pozri si výsledky.'}</p></article>`}
function polls(){const all=data('polls'),items=filter==='Všetky'?all:all.filter(p=>p.kind===filter);return `<div class="page polls">${hero('polls','HLASUJ.','', '<h2>TVOR NITRU.</h2>')}${chips(['Všetky',...new Set(all.map(p=>p.kind).filter(Boolean))])}<div class="cards">${status('polls','Momentálne nie je zverejnená žiadna anketa.')||items.map(pollCard).join('')||'<p class="empty">V tejto kategórii zatiaľ nič nie je.</p>'}</div></div>`}
const date=s=>{const d=new Date(s);return Number.isNaN(d.getTime())?esc(s):d.toLocaleDateString('sk-SK',{day:'numeric',month:'numeric',year:'numeric'})}
function category(e){const t=`${e.title} ${e.performer}`.toLowerCase();return /festival/.test(t)?'Festivaly':/koncert/.test(t)?'Koncerty':'Párty'}
function events(){const items=data('events').filter(e=>filter==='Všetky'||category(e)===filter);return `<div class="page events">${hero('events','KAM|DNES?','<span style="color:var(--blue)">NITRA ŽIJE.</span>')}${chips(['Všetky','Koncerty','Festivaly','Párty'])}<div class="cards">${status('events','Aktuálne tu nie sú žiadne eventy.')||items.map(e=>`<article class="card event-card">${e.image?`<img src="${esc(e.image)}" alt="" loading="lazy">`:ornament()}<button class="circle" data-event="${esc(e.id)}" aria-label="Detail ${esc(e.title)}">${icon('arrow')}</button><button class="event-content" data-event="${esc(e.id)}" style="text-align:left"><time>${date(e.date)}</time><h2>${esc(e.title)}</h2><p>${esc(e.place)}</p></button><div class="tags"><span>${esc(e.organizer||'Nitra')}</span><span>${category(e)}</span></div></article>`).join('')||'<p class="empty">V tejto kategórii nie sú eventy.</p>'}</div></div>`}
const avatar=p=>p.avatarUrl?`<img class="avatar" src="${esc(p.avatarUrl)}" alt="${esc(p.name)}">`:`<span class="avatar">${esc((p.name||'N').slice(0,1))}</span>`
function people(){const items=data('people').filter(p=>filter==='Všetci'||(p.interests||[]).includes(filter));return `<div class="page people">${hero('people','SPOZNAJ|ĽUDÍ|Z NITRY.','SKUTOČNÍ ĽUDIA.<br>ŽIADNE MASKY.')}${chips(['Všetci',...new Set(data('people').flatMap(p=>p.interests||[]))].slice(0,10))}<div class="cards">${status('people','Profily zatiaľ nie sú dostupné. Prihlás sa a nastav svoj matching profil.')||items.map(p=>`<article class="card person-card">${p.photoUrl||p.avatarUrl?`<img src="${esc(p.photoUrl||p.avatarUrl)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="avatar-placeholder">${esc((p.name||'N').slice(0,1))}</div>`}<div class="person-top"><span>${p.verified?'OVERENÝ PROFIL':'NITRA SPACE'}</span><button class="circle" data-profile="${esc(p.username)}" aria-label="Otvoriť profil ${esc(p.name)}">${icon('arrow')}</button></div><div><h2>${esc(p.name)}${p.age?`, ${esc(p.age)}`:''}</h2><div class="tags">${(p.interests||[]).slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div><button class="circle like" data-match="${esc(p.id)}" aria-label="Záujem o ${esc(p.name)}">${icon('heart')}</button></div></article>`).join('')||'<p class="empty">Žiadny profil s týmto záujmom.</p>'}</div><a class="outline" style="margin-top:18px" href="#account">Nastaviť môj profil${icon('arrow')}</a></div>`}
function auth(){return `<form class="auth" data-form="auth"><h2>${register?'Vytvor si účet.':'Vitaj späť.'}</h2>${register?'<label>Meno<input name="name" required maxlength="80" autocomplete="name"></label><label>Používateľské meno<input name="username" pattern="[a-z0-9_]{3,24}" required autocomplete="username"></label><label>Dátum narodenia (16+)<input type="date" name="birthDate" required></label>':''}<label>Email<input type="email" name="email" required autocomplete="email"></label><label>Heslo<input type="password" name="password" required minlength="8" autocomplete="${register?'new-password':'current-password'}"></label><p class="form-message" role="alert"></p><button class="primary">${register?'Vytvoriť účet':'Prihlásiť sa'}${icon('arrow')}</button><button type="button" class="small-action" data-action="auth-toggle">${register?'Už mám účet':'Nemáš účet? Zaregistruj sa'}</button></form>`}
function accountPage(){const p=account();return `<div class="page account">${hero('account','TVOJ|PRIESTOR.','VŠETKO POD KONTROLOU.')}<div class="account-content">${p?`<div class="identity">${avatar(p)}<div><strong>${esc(p.name)}</strong><p>@${esc(p.username)}</p></div></div><button class="outline" data-action="edit">Upraviť profil${icon('arrow')}</button><div class="settings">${[['edit','user','Profil'],['matching-setup','heart','Matching profil'],['privacy','lock','Súkromie'],['security','lock','Bezpečnosť'],['signout','logout','Odhlásiť sa']].map(([a,i,label])=>`<button data-action="${a}">${icon(i)}${label}<span class="chevron">${icon('chevron')}</span></button>`).join('')}<a href="/account">${icon('user')}Rozšírené nastavenia a fotky<span class="chevron">${icon('arrow')}</span></a></div>`:cache.account?.status==='error'?`<div class="empty">${esc(cache.account.error)}<button data-action="retry">Skúsiť znova</button></div>`:auth()}</div></div>`}
function render(){document.querySelector('#main').innerHTML=({board:home,chat,polls,events,people,account:accountPage}[route]||home)()}
async function load(){const id=++generation;const names=route==='board'?['events','polls','people','account']:route==='chat'?['people','account']:[route,'account'];await Promise.all([...new Set(names)].map(async n=>{const method={events:'loadEvents',polls:'loadPolls',people:'loadPeople',account:'loadAccount'}[n];if(!method)return;const result=await api[method]();if(id!==generation)return;cache[n]=result;render()}))}
function navigate(){
 cleanupFeature();generation++;
 const next=location.hash.slice(1).split('?')[0],path=location.pathname;
 const feature=/^\/(news|polls|people|account|messages|activity|admin)(\/|$)/.test(path)?path:
 ({news:'/news',people:'/people',account:'/account',polls:'/polls'}[next]||((!next||next==='board')&&(path==='/'||path==='/chrome-preview.html')?'/board':''));
 route=feature?feature.split('/')[1]:(routes[next]?next:'board');filter='Všetky';
 if(sheet.open)sheet.close();shell();window.scrollTo(0,0);
 if(feature){
  document.querySelector('#main').innerHTML='<div class="editorial"><p id="feature-notice" role="status" aria-live="polite"></p><div id="feature-content"><p class="empty">Načítavam…</p></div></div>';
  mountFeature(client,feature,go);
 }else{render();load()}
}
function go(url){history.pushState({},'',url);navigate()}
document.addEventListener('click',event=>{
 const a=event.target.closest('a[href]');if(!a||event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||a.target||a.hasAttribute('download'))return;
 const url=new URL(a.href,location.href);
 if(url.origin!==location.origin||!(/^\/(news|polls|people|account|messages|activity|admin)(\/|$)/.test(url.pathname)||url.pathname==='/'&&url.hash))return;
 event.preventDefault();go(url.pathname+url.search+url.hash);
});
window.addEventListener('popstate',navigate);
window.addEventListener('nitra-auth-change',()=>{cache.account=null});
function modal(title,body){returnFocus=document.activeElement;sheet.innerHTML=`<button class="circle close" data-action="close" aria-label="Zavrieť">${icon('close')}</button><h2>${esc(title)}</h2>${body}`;if(!sheet.open)sheet.showModal()}
function needUser(){if(account())return true;location.hash='account';toast('Najprv sa prihlás do svojho účtu.');return false}
async function profile(username){modal('Načítavam profil…','');const result=await api.loadProfile(username);if(!sheet.open)return;if(result.status!=='ready'){sheet.innerHTML=`<button class="circle close" data-action="close" aria-label="Zavrieť">${icon('close')}</button><p class="empty">${esc(result.error||'Profil nie je dostupný.')}</p>`;return}const p=result.data;modal(p.name,`${(p.photos||[]).map(photo=>`<img class="detail-photo" src="${esc(photo.url)}" alt="Fotografia ${esc(p.name)}">`).join('')}<p class="muted">@${esc(p.username)}</p><p style="margin:16px 0;line-height:1.6">${esc(p.intro||p.bio||'Profil ešte nemá predstavenie.')}</p><div class="tags">${p.interests.map(t=>`<span>${esc(t)}</span>`).join('')}</div><button class="primary" data-match="${esc(p.id)}">Mám záujem${icon('heart')}</button>`)}
async function action(name){const p=account();if(name==='close'){sheet.close();return}if(name==='retry'){cache={};render();load();return}if(name==='auth-toggle'){register=!register;render();return}if(name==='search'){modal('Nájdi svoj space.','<label>Hľadať sekcie, eventy a ľudí<input id="search" type="search" placeholder="Meno, event, ankety…" autocomplete="off"></label><div id="search-results"></div>');return}if(name==='signout'){await api.signOut();cache={};navigate();return}if(!needUser())return;if(name==='security'){modal('Bezpečnosť.','<p class="muted">Zmenu hesla a vymazanie účtu nájdeš v existujúcich zabezpečených nastaveniach.</p>'+button('/account','Otvoriť nastavenia'));return}if(name==='matching-setup'){modal('Matching profil.','<p class="muted">Fotky, záujmy a sprievodca nastavením zostávajú dostupné v tvojom existujúcom účte.</p>'+button('/account','Fotky a matching'));return}if(name==='edit'||name==='privacy')modal(name==='edit'?'Tvoj profil.':'Súkromie.',`<form data-form="profile">${name==='edit'?`<label>Meno<input name="name" required maxlength="80" value="${esc(p.name)}"></label><label>Používateľské meno<input name="username" pattern="[a-z0-9_]{3,24}" required value="${esc(p.username)}"></label><label>O mne<textarea name="bio" maxlength="500">${esc(p.bio)}</textarea></label><label>Záujmy oddelené čiarkou<input name="interests" value="${esc(p.interests.join(', '))}"></label>`:`<label><input type="checkbox" name="discoverable" ${p.discoverable?'checked':''}>Zobrazovať môj profil ľuďom</label><label><input type="checkbox" name="showOnline" ${p.showOnline?'checked':''}>Zobrazovať môj online stav</label>`}<p class="form-message" role="alert"></p><button class="primary">Uložiť zmeny${icon('arrow')}</button></form>`)}
document.addEventListener('click',async ev=>{const el=ev.target.closest('button,[data-profile]');if(!el)return;try{if(el.dataset.action)await action(el.dataset.action);if(el.dataset.filter){filter=el.dataset.filter;render()}if(el.dataset.event){const e=data('events').find(x=>String(x.id)===el.dataset.event);if(e)modal(e.title,`${e.image?`<img class="detail-photo" src="${esc(e.image)}" alt="${esc(e.title)}">`:''}<p class="muted">${date(e.date)} · ${esc(e.place)}</p><p style="margin-top:14px">${esc(e.organizer||'')}<br>${esc(e.performer||'')}</p>${e.link?`<a class="primary" href="${esc(e.link)}" target="_blank" rel="noopener noreferrer">Zdroj / vstupenky${icon('arrow')}</a>`:''}`)}if(el.dataset.profile)await profile(el.dataset.profile);if(el.dataset.poll&&needUser()){el.disabled=true;await api.vote(el.dataset.poll,el.dataset.option);cache.polls=await api.loadPolls();if(route==='polls')render();toast('Hlas je uložený. Ďakujeme.')}if(el.dataset.match&&needUser()){el.disabled=true;const r=await api.requestMatch(el.dataset.match);toast(r.status==='connected'?'Máte spojenie! Nájdeš ho v aktivite účtu.':'Záujem bol odoslaný.')}}catch(e){toast(e.message||'Akciu sa nepodarilo dokončiť.')}finally{if(el.isConnected)el.disabled=false}})
document.addEventListener('submit',async ev=>{const form=ev.target;if(!form.dataset.form)return;ev.preventDefault();const submit=form.querySelector('[type=submit],.primary'),message=form.querySelector('.form-message');submit.disabled=true;message.textContent='';try{const fields=Object.fromEntries(new FormData(form));if(form.dataset.form==='auth'){const r=await api[register?'signUp':'signIn'](fields);if(r.confirmationRequired){message.textContent='Skontroluj email a potvrď registráciu.';return}cache.account=await api.loadAccount();render();toast('Si prihlásený.')}else{if(form.elements.interests)fields.interests=fields.interests.split(',');if(form.elements.discoverable){fields.discoverable=form.elements.discoverable.checked;fields.showOnline=form.elements.showOnline.checked}await api.updateProfile(fields);cache.account=await api.loadAccount();sheet.close();render();toast('Profil je uložený.')}}catch(e){message.textContent=e.message||'Niečo sa nepodarilo.'}finally{submit.disabled=false}})
document.addEventListener('input',ev=>{if(ev.target.id!=='search')return;const q=ev.target.value.toLocaleLowerCase('sk').trim();const items=[...Object.entries(routes).map(([id,label])=>({label,href:'#'+id})),...data('events').map(e=>({label:e.title,href:'#events'})),...data('people').map(p=>({label:p.name,href:'#people'}))];document.querySelector('#search-results').innerHTML=items.filter(x=>x.label.toLocaleLowerCase('sk').includes(q)).slice(0,10).map(x=>`<a class="search-result" href="${x.href}">${esc(x.label)}</a>`).join('')||'<p class="muted">Nič sa nenašlo.</p>'})
sheet.addEventListener('close',()=>returnFocus?.isConnected&&returnFocus.focus());sheet.addEventListener('click',e=>{if(e.target.closest('a[href^="#"]'))sheet.close()})
window.addEventListener('hashchange',navigate);document.addEventListener('visibilitychange',()=>{document.documentElement.dataset.paused=String(document.hidden)})
navigate()
