create table if not exists private.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists private.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('verify', 'unverify', 'ban', 'unban')),
  created_at timestamptz not null default now()
);

alter table private.admin_users enable row level security;
alter table private.admin_audit_log enable row level security;
revoke all on private.admin_users, private.admin_audit_log from public, anon, authenticated;

alter table public.profiles
  add column if not exists is_verified boolean not null default false,
  add column if not exists verified_at timestamptz;

insert into private.admin_users(user_id)
select id
from auth.users
where lower(email) = lower('dodesko09za@gmail.com')
on conflict (user_id) do nothing;

create or replace function private.is_admin(p_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_user is not null and exists (
    select 1 from private.admin_users a where a.user_id = p_user
  );
$$;

create or replace function private.verified_account_ids()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(jsonb_agg(p.id order by p.id), '[]'::jsonb)
  from public.profiles p
  where (select auth.uid()) is not null and p.is_verified;
$$;

create or replace function private.admin_list_users(p_query text default '', p_limit integer default 100)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_admin uuid := auth.uid();
  v_query text := lower(trim(coalesce(p_query, '')));
  v_result jsonb;
begin
  if not private.is_admin(v_admin) then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb)
  into v_result
  from (
    select
      u.id,
      u.email,
      u.created_at,
      u.last_sign_in_at,
      (u.banned_until is not null and u.banned_until > now()) as is_banned,
      p.username,
      p.display_name,
      p.avatar_path,
      p.is_verified,
      private.is_admin(u.id) as is_admin
    from auth.users u
    left join public.profiles p on p.id = u.id
    where v_query = ''
       or lower(coalesce(u.email, '')) like '%' || v_query || '%'
       or lower(coalesce(p.username, '')) like '%' || v_query || '%'
       or lower(coalesce(p.display_name, '')) like '%' || v_query || '%'
    order by u.created_at desc
    limit least(greatest(coalesce(p_limit, 100), 1), 200)
  ) x;

  return v_result;
end;
$$;

create or replace function private.admin_set_verified(p_target uuid, p_verified boolean)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_admin uuid := auth.uid();
begin
  if not private.is_admin(v_admin) then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  update public.profiles
  set is_verified = coalesce(p_verified, false),
      verified_at = case when coalesce(p_verified, false) then now() else null end
  where id = p_target;

  if not found then
    raise exception 'Profile not found' using errcode = 'P0002';
  end if;

  insert into private.admin_audit_log(admin_user_id, target_user_id, action)
  values (v_admin, p_target, case when coalesce(p_verified, false) then 'verify' else 'unverify' end);
end;
$$;

create or replace function private.admin_target_is_admin(p_target uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_admin(auth.uid()) then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  return private.is_admin(p_target);
end;
$$;

create or replace function private.admin_record_ban(p_admin uuid, p_target uuid, p_banned boolean)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  if not private.is_admin(p_admin) then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  insert into private.admin_audit_log(admin_user_id, target_user_id, action)
  values (p_admin, p_target, case when p_banned then 'ban' else 'unban' end);
end;
$$;

create or replace function public.is_admin()
returns boolean language sql stable security invoker set search_path = ''
as $$ select private.is_admin(auth.uid()); $$;

create or replace function public.verified_account_ids()
returns jsonb language sql stable security invoker set search_path = ''
as $$ select private.verified_account_ids(); $$;

create or replace function public.admin_list_users(p_query text default '', p_limit integer default 100)
returns jsonb language sql stable security invoker set search_path = ''
as $$ select private.admin_list_users(p_query, p_limit); $$;

create or replace function public.admin_set_verified(p_target uuid, p_verified boolean)
returns void language sql volatile security invoker set search_path = ''
as $$ select private.admin_set_verified(p_target, p_verified); $$;

create or replace function public.admin_target_is_admin(p_target uuid)
returns boolean language sql stable security invoker set search_path = ''
as $$ select private.admin_target_is_admin(p_target); $$;

create or replace function public.admin_record_ban(p_admin uuid, p_target uuid, p_banned boolean)
returns void language sql volatile security invoker set search_path = ''
as $$ select private.admin_record_ban(p_admin, p_target, p_banned); $$;

revoke all on function private.is_admin(uuid), private.verified_account_ids(),
  private.admin_list_users(text, integer), private.admin_set_verified(uuid, boolean),
  private.admin_target_is_admin(uuid), private.admin_record_ban(uuid, uuid, boolean)
  from public, anon;
grant execute on function private.is_admin(uuid), private.verified_account_ids(),
  private.admin_list_users(text, integer), private.admin_set_verified(uuid, boolean),
  private.admin_target_is_admin(uuid) to authenticated;
grant execute on function private.admin_record_ban(uuid, uuid, boolean) to service_role;

revoke all on function public.is_admin(), public.verified_account_ids(),
  public.admin_list_users(text, integer), public.admin_set_verified(uuid, boolean),
  public.admin_target_is_admin(uuid), public.admin_record_ban(uuid, uuid, boolean)
  from public, anon;
grant execute on function public.is_admin(), public.verified_account_ids(),
  public.admin_list_users(text, integer), public.admin_set_verified(uuid, boolean),
  public.admin_target_is_admin(uuid) to authenticated;
grant execute on function public.admin_record_ban(uuid, uuid, boolean) to service_role;
